/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name varchar(20) NOT NULL,
    date_of_birth DATE NOT NULL,
    escape_attempts INTEGER NOT NULL,
    neutered BOOLEAN NOT NULL,
    weight_kg DECIMAL NOT NULL
);

ALTER TABLE animals ADD COLUMN species VARCHAR(50);

/*
                                      Table "public.animals"
     Column      |         Type          | Collation | Nullable |             Default
-----------------+-----------------------+-----------+----------+----------------------------------
 id              | integer               |           | not null | generated by default as identity
 name            | character varying(20) |           | not null |
 date_of_birth   | date                  |           | not null |
 escape_attempts | integer               |           | not null |
 neutered        | boolean               |           | not null |
 weight_kg       | numeric               |           | not null |
 species         | character varying(50) |           |          |
Indexes:
    "animals_pkey" PRIMARY KEY, btree (id)
*/